version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:demos@db/trello_test

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment: 
      - POSTGRES_DB=trello_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=demos
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
